import { createPoemLoader, filterPoems, parseStored, sanitizeSettings } from '../reader-core.js';
import { escapeHTML, layoutReadingPage, notesMarkup, verses } from '../reader-renderer.js?v=0.6.16';
const $=id=>document.getElementById(id), storageKey='reader.volume-2.review.v1';
const saved=parseStored(localStorage.getItem(storageKey),{}),settings=sanitizeSettings(saved.settings);
const state={poems:[],filtered:[],current:null,detail:null,sequence:0,limit:30,favorites:new Set(saved.favorites||[]),readIDs:new Set(saved.readIDs||[]),bookmarks:saved.bookmarks||{},settings};
const rootURL=new URL('../',import.meta.url),assetURL=path=>new URL(path,rootURL).href;
const loader=createPoemLoader(async id=>{const response=await fetch(assetURL(`data/reader-volume-2/poems/${encodeURIComponent(id)}.json`));if(!response.ok)throw Error('诗文暂未载入');return response.json();});
function persist(){try{localStorage.setItem(storageKey,JSON.stringify({settings:state.settings,favorites:[...state.favorites],readIDs:[...state.readIDs],bookmarks:state.bookmarks,selectedID:state.current?.id}));}catch{}}
function saveOffset(){const body=$('page').querySelector('.poem-body');if(body&&state.current&&state.detail?.id===state.current.id){state.bookmarks[state.current.id]=body.scrollTop;persist();}}
function navigation(){const index=state.filtered.findIndex(p=>p.id===state.current?.id);$('previous').disabled=index<=0;$('next').disabled=index<0||index>=state.filtered.length-1;$('pageCount').textContent=index<0?'':`${index+1} / ${state.filtered.length}`;$('favorite').setAttribute('aria-pressed',String(state.favorites.has(state.current?.id)));$('favorite').textContent=state.favorites.has(state.current?.id)?'已收藏':'收藏';$('markRead').setAttribute('aria-pressed',String(state.readIDs.has(state.current?.id)));$('markRead').textContent=state.readIDs.has(state.current?.id)?'已读 · 点此取消':'标记已读';}
function renderList(){const items=$('items');items.replaceChildren();for(const p of state.filtered.slice(0,state.limit)){const button=document.createElement('button');button.className='review-item';button.type='button';button.dataset.id=p.id;button.setAttribute('aria-current',String(p.id===state.current?.id));const image=document.createElement('img');image.src=assetURL(p.thumbnail);image.alt='';image.loading='lazy';const text=document.createElement('div'),title=document.createElement('span'),author=document.createElement('small');title.textContent=p.title;author.textContent=`${p.author} · ${String(p.order).padStart(3,'0')}`;text.append(title,author);button.append(image,text);button.onclick=()=>show(p);items.append(button);}$('moreResults').hidden=state.limit>=state.filtered.length;$('resultCount').textContent=state.filtered.length?`${state.filtered.length} 首诗篇`:'没有匹配的诗篇';navigation();}
function filter(){const collection=$('collection').value;state.filtered=filterPoems(state.poems,{query:$('search').value,category:$('genre').value||'all',collection:collection==='favorites'?'favorites':'all',readStatus:['read','unread'].includes(collection)?collection:'all'},state.favorites,state.readIDs);state.limit=30;renderList();if(state.filtered.length&&!state.filtered.some(p=>p.id===state.current?.id))show(state.filtered[0]);}
function layout(){const sample=$('sample'),page=$('page');sample.dataset.note=String(state.settings.notes);sample.dataset.words=String($('showWords').checked);if(!state.detail)return;layoutReadingPage(page,state.detail,{width:sample.clientWidth,height:sample.clientHeight,fontSize:state.settings.fontSize,notesEnabled:state.settings.notes});}
async function show(p){saveOffset();const sequence=++state.sequence;state.current=p;state.detail=null;persist();history.replaceState(null,'',`#${p.order}`);document.title=`${p.title} · 第二卷`;$('page').setAttribute('aria-busy','true');$('page').innerHTML='<p class="page-message">载入诗文…</p>';navigation();try{const detail=await loader.load(p.id);if(sequence!==state.sequence)return;state.detail=detail;const page=$('page');page.innerHTML=`<figure class="scene" aria-hidden="true"><img src="${escapeHTML(assetURL(p.image))}" alt="" decoding="async"></figure><div class="book-ribbon">${escapeHTML(p.genre)}</div><div class="poem-body" tabindex="0" aria-label="${escapeHTML(p.title)}全文"><div class="poem-text"><h2 class="poem-title">${escapeHTML(p.title)}</h2><p class="poem-author">${escapeHTML(p.dynasty)} · ${escapeHTML(p.author)}</p><div class="poem-lines">${verses(detail.rubyLines)}</div></div><section class="note"><h3>诗意</h3><p>${escapeHTML(detail.note)}</p><button class="note-more" aria-label="展开完整诗意和注释">展开</button></section></div>`;page.setAttribute('aria-busy','false');page.querySelector('.note-more').onclick=openNotes;layout();page.querySelector('.poem-body').scrollTop=Number(state.bookmarks[p.id])||0;page.querySelector('.poem-body').addEventListener('scroll',()=>{clearTimeout(state.scrollTimer);state.scrollTimer=setTimeout(saveOffset,200);},{passive:true});page.querySelector('.scene img').onerror=()=>{$('status').textContent='插画暂未载入，可继续阅读诗文';};renderList();}catch(error){if(sequence!==state.sequence)return;$('page').setAttribute('aria-busy','false');$('page').innerHTML=`<div class="page-message">${escapeHTML(error.message)}<br><button type="button">重试</button></div>`;$('page').querySelector('button').onclick=()=>show(p);}}
function openNotes(){if(!state.detail)return;const detail=state.detail;$('notesTitle').textContent=detail.title;$('fullNotes').innerHTML=notesMarkup(detail)+(detail.editorialNotes.length?`<section class="notes-section"><h3>校勘与释义说明</h3>${detail.editorialNotes.map(text=>`<p>${escapeHTML(text)}</p>`).join('')}</section>`:'');const urls=detail.sourceRefs.filter(url=>{try{return ['http:','https:'].includes(new URL(url).protocol);}catch{return false;}});if(urls.length){const section=document.createElement('section');section.className='notes-section';const h=document.createElement('h3');h.textContent='整理依据';section.append(h);for(const [i,url] of urls.entries()){const p=document.createElement('p'),a=document.createElement('a');a.href=url;a.target='_blank';a.rel='noopener';a.textContent=`来源 ${i+1}`;p.append(a);section.append(p);}$('fullNotes').append(section);}$('fullNotes').scrollTop=0;$('notesDialog').showModal();}
function turn(offset){const index=state.filtered.findIndex(p=>p.id===state.current?.id),p=state.filtered[index+offset];if(p)show(p);}
$('previous').onclick=()=>turn(-1);$('next').onclick=()=>turn(1);$('notes').onclick=openNotes;$('closeNotes').onclick=()=>$('notesDialog').close();
$('search').oninput=filter;$('genre').onchange=filter;$('collection').onchange=filter;$('moreResults').onclick=()=>{state.limit+=30;renderList();};
$('favorite').onclick=()=>{if(!state.current)return;const id=state.current.id;state.favorites.has(id)?state.favorites.delete(id):state.favorites.add(id);persist();filter();};
$('markRead').onclick=()=>{if(!state.current)return;const id=state.current.id;state.readIDs.has(id)?state.readIDs.delete(id):state.readIDs.add(id);persist();filter();};
$('fontSize').value=String(settings.fontSize);$('showNote').checked=settings.notes;
$('fontSize').onchange=()=>{saveOffset();state.settings.fontSize=+$('fontSize').value;layout();persist();};$('showNote').onchange=()=>{state.settings.notes=$('showNote').checked;layout();persist();};$('showWords').onchange=layout;
$('screen').onchange=()=>{const [width,height]=$('screen').value.split(',').map(Number);$('sample').style.setProperty('--sample-width',`${width}px`);$('sample').style.setProperty('--sample-height',`${height}px`);layout();};
new ResizeObserver(layout).observe($('sample'));document.addEventListener('keydown',event=>{if(['INPUT','SELECT','TEXTAREA'].includes(event.target.tagName)||$('notesDialog').open)return;if(event.key==='ArrowLeft'){event.preventDefault();turn(-1);}if(event.key==='ArrowRight'){event.preventDefault();turn(1);}});window.addEventListener('pagehide',saveOffset);
try{const response=await fetch(assetURL('data/reader-volume-2/catalog.json'));if(!response.ok)throw Error('阅读资料暂未就绪');const data=await response.json();state.poems=[...data.poems].sort((a,b)=>a.order-b.order);$('status').textContent=`${data.poems.length} 首 · 图文阅读校样`;for(const section of data.sections){const option=document.createElement('option');option.value=section;option.textContent=section;$('genre').append(option);}state.filtered=state.poems;const order=+location.hash.slice(1),first=state.poems.find(p=>p.order===order)||state.poems.find(p=>p.id===saved.selectedID)||state.poems.find(p=>p.order===1)||state.poems[0];renderList();await show(first);}catch(error){$('status').textContent=error.message;$('page').innerHTML=`<p class="page-message">${escapeHTML(error.message)}</p>`;}
